### ISSUE TITLE
question about code

### ISSUE THREAD

**Issue by zzwjames** [AntigoneRandy/QuantBackdoor_EFRAP#1]
Hi:

Thanks for your great work. I am wondering have you released the code?

Best,

**Comment by AntigoneRandy** [comment]
Hi @zzwjames, thanks for your kind interest. We are still sorting out our code and it is expected to be released at the end of this month. We will let you know once it is released.

**Comment by AntigoneRandy** [comment]
Hi dear @zzwjames, we have uploaded our code and opensourced the malicious models for testing. Please kindly check it!

**Comment by zzwjames** [comment]
> Hi dear @zzwjames, we have uploaded our code and opensourced the malicious models for testing. Please kindly check it!

Thank you for your update!
