### ISSUE TITLE
from torch.quantization.fx.fusion_patterns import ConvBNReLUFusion, ModuleReLUFusion

### ISSUE THREAD

**Issue by bieyl** [AntigoneRandy/QuantBackdoor_EFRAP#2]
ImportError: cannot import name "ConvBNReLUFusion“ from "torch.quantization.fx.fusion_patterns
请问是不是mqbench和pytorch版本不匹配

**Comment by AntigoneRandy** [comment]
Hi dear @bieyl, thanks for your interest in our work. It is indeed possibly beacuse of the version mismatch between torch and mqbench. Similar problem was previously reported in [this issue](https://github.com/ModelTC/MQBench/issues/268), and you may refer to it for possible solutions.
