### ISSUE TITLE
How to train the model

### ISSUE THREAD

**Issue by yansuoyuli** [AntigoneRandy/QuantBackdoor_EFRAP#4]
Thanks for your awesome work!
I am writing to ask about how the train the model from beginning?

**Comment by AntigoneRandy** [comment]
Hi, @yansuoyuli, thanks for your interest in our work. We directly use the official code from three QCB attacks. Please find more details in our paper appendix section A (https://openaccess.thecvf.com/content/CVPR2024/supplemental/Li_Nearest_is_Not_CVPR_2024_supplemental.pdf).
